# Generated by Django 2.1.4 on 2019-01-07 09:26

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=64)),
                ('lat', models.FloatField(max_length=20)),
                ('lng', models.FloatField(max_length=20)),
                ('country', models.CharField(max_length=45)),
                ('pt', django.contrib.gis.db.models.fields.PointField(default=False, srid=4326, verbose_name='loc')),
            ],
        ),
    ]
